repos:
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      exclude: ^(migrations/|frontend/|scripts/)
      types: [python]
      verbose: true
-   repo: https://github.com/timothycrosley/isort
    rev: 5.9.2
    hooks:
    - id: isort
      exclude: ^(migrations/|frontend/|scripts/)
      types: [python]
      verbose: true
      args:
          - --profile
          - black
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
    - id: prettier
      files: ^(frontend/src/)